//Generated by TheSDK/halfband.export_scala
package halfband_BW_01125_N_6

object halfband_BW_01125_N_6 {

val H=Seq(-0.00682504,  0,          0.0394589 ,  0,         -0.14259413,  0,
                            0.60979372,  1,          0.60979372,  0,         -0.14259413,  0,
                            0.0394589 ,  0,         -0.00682504)
 }
